server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

cache:
  string-cache:
    maxCapacity: 5
  uuid-cache:
    maxCapacity: 5